# .bashrc by @mcking-07

# if not running interactively, don't do anything
[[ $- != *i* ]] && return

# set term for better colours
TERM="xterm-256color"

# history config
HISTCONTROL=ignoreboth # no duplicates or lines starting with a space in the history 
HISTSIZE=2000 # set number of lines in the history
HISTFILESIZE=2000 # set the history file size

# shopt config
shopt -s autocd # change to named directory
shopt -s cdspell # autocorrects cd misspellings
shopt -s cmdhist # save multi-line commands in history as single line
shopt -s dotglob # include hidden files during filename expansion
shopt -s histappend # do not overwrite history
shopt -s expand_aliases # expand aliases
shopt -s checkwinsize # checks term size when bash regains control

# ignore case during tab completion
bind "set completion-ignore-case on"

# enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# autojump config
if command -v autojump &>/dev/null; then
  . /usr/share/autojump/autojump.sh
fi

# custom prompt for bash
export PS1="\[$(tput bold)\]\[\033[38;5;10m\]\u\[$(tput sgr0)\]:\[$(tput sgr0)\]\[\033[1;34m\]\W\[$(tput sgr0)\]\n\[$(tput sgr0)\]\[$(tput bold)\]\[\033[38;5;14m\]>\[$(tput sgr0)\] \[$(tput sgr0)\]"

# nala config
if command -v nala &>/dev/null; then
  apt() {
    command nala "$@"
  }

  sudo() {
    if [ "$1" = "apt" ]; then
      shift
      command sudo nala "$@"
    else
      command sudo "$@"
    fi
  }
fi

# starship init
if command -v starship &>/dev/null; then
  export STARSHIP_CONFIG=~/.config/starship/starship.toml
  eval "$(starship init bash)"
fi
